name: Build Image

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      -  master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install Docker
        run: |
          # Download and install Packer.
          #curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          #sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          #sudo apt-get update && sudo apt-get install packer
          #packer --version
          echo "hello"

      - name: Build Docker Image
        run: |
          echo "docker build . -t node-media-server"
          curl https://raw.githubusercontent.com/soluble-ai/soluble-cli/master/linux-install.sh | sh
          ./soluble auth profile
          ./soluble image-scan --image illuspas/node-media-server --upload 
    env:
      SOLUBLE_API_TOKEN: ${{ secrets.SOLUBLE_API_TOKEN }}
      SOLUBLE_ORG_ID: ${{ secrets.SOLUBLE_ORG_ID }}
      #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
